/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/chess_pieces/knight/scene.gltf -o src/components/Knight.jsx -r public 
Author: marcelo.medeirossilva (https://sketchfab.com/marcelo.medeirossilva)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-chess-knight-112534cb4cbb47588c2cf566441f37fc
Title: Low Poly Chess - Knight
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { a } from '@react-spring/three';

export function Knight(props) {
  const { nodes, materials } = useGLTF('/chess_pieces/knight/scene.gltf')
  const groupRef = useRef();

  useFrame(() => {
      // Rotar la escena continuamente
      //Puedes ajustar la velocidad de rotación aquí
      groupRef.current.rotation.z += 0.005;
  });

  return (
    <a.group {...props} dispose={null}>
      <a.group rotation={[-Math.PI / 2, 0, 0]} scale={0.25}>
        <mesh geometry={nodes.Chess_Knight_0.geometry} ref={groupRef} material={materials.Root} position={[0, 0.082, 2.523]} />
      </a.group>
    </a.group>
  )
}

useGLTF.preload('/chess_pieces/knight/scene.gltf')
