/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/chess_pieces/rook/scene.gltf -o src/components/Rook.jsx -r public 
Author: marcelo.medeirossilva (https://sketchfab.com/marcelo.medeirossilva)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-chess-rook-cbd416e785f64648bff3675fd45b3594
Title: Low Poly Chess - Rook
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { a } from '@react-spring/three';

export function Rook(props) {
  const { nodes, materials } = useGLTF('/chess_pieces/rook/scene.gltf')

  const groupRef = useRef();

  useFrame(() => {
      // Rotar la escena continuamente
      //Puedes ajustar la velocidad de rotación aquí
      groupRef.current.rotation.z += 0.005;
  });
  return (
    <a.group {...props} dispose={null}>
      <a.group rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
        <a.mesh geometry={nodes.Chess_Rook_0.geometry} ref={groupRef} material={materials.Root} position={[0, 0, 2.725]} />
      </a.group>
    </a.group>
  )
}

useGLTF.preload('/chess_pieces/rook/scene.gltf')
